version: '3.4'

services:
  db:
    image: postgres
    expose:
      - 5432
    env_file:
      - ./.env.dev
  kineticmodelssite:
    image: kineticmodelssite
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:5678 --nothreading --noreload"]
    env_file:
      - ./.env.dev
    ports:
      - "5678:5678"
    depends_on:
      - db
