version: "3.8"

services:
  db:
    image: postgres
    expose:
      - 5432
    env_file:
      - ./.env
  web:
    build: .
    command: ./bin/entrypoint.sh
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
      - rmg-models:/app/rmg-models
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "8000:80"
    depends_on:
      - web
volumes:
  static:
  media:
  rmg-models:
    external: true
