version: "3.8"

services:
  db:
    image: postgres
    expose:
      - 5432
    env_file:
      - ./.env.dev
  debug:
    build: .
    command: ./bin/runserver.sh
    env_file:
      - ./.env.dev
    volumes:
      - .:/app
      - rmg-models:/app/rmg-models
      - conda:/kms_env
    ports:
      - "5678:5678"
      - "8080:8080"
    depends_on:
      - db
volumes:
  rmg-models:
    external: True
  conda:
    external: True
