version: "3.7"

services:
  db:
    image: postgres
    env_file: .env
  web:
    build: .
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
      - rmg-models:/app/rmg-models
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  static:
  media:
  rmg-models:
    external: true
