version: "3.8"

services:
  db:
    image: postgres
    expose:
      - 5432
    env_file:
      - ${ENV_FILE}
  web:
    build: .
    volumes:
      - .:/app
      - kms-static:/app/static
      - kms-media:/app/media
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - ENV_FILE
volumes:
  kms-static:
  kms-media:
