version: "3.8"

services:
  db:
    image: postgres
    expose:
      - 5432
  web:
    build: .
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.${ENV}
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "8000:80"
    depends_on:
      - web
volumes:
  static:
  media:
