name: rmg_env
channels:
  - defaults
  - rmg
dependencies:
  - libgcc # [unix]
  - python
  - numpy >=1.10.0
  - cython >=0.25.2
  - matplotlib >=1.5
  - rdkit >=2015.09.2
  - pydas
  - pydqed
  - quantities
  - scipy
  - xlwt
  - markupsafe
  - jinja2
  - pyparsing
  - pydot ==1.2.2
  - nose
  - coverage
  - gprof2dot
  - cairo
  - cairocffi
  - openbabel
  - psutil
  - symmetry
  - mopac
  - graphviz
  - django ==1.8.4
  - beautifulsoup4
  - xlrd
  - docutils