name: rmg_env
channels:
  - defaults
  - rmg
dependencies: # Only those in addition to normal RMG
  - xlrd
  - xlwt
  - markupsafe
  - jinja2
  - cairo
  - cairocffi
  - openbabel
  - psutil
  - graphviz
  - django
  - beautifulsoup4
  - docutils