name: KMS Build
on:
  push:
    branches: [ master ]
jobs:
  kms_build:
    name: KMS Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build -f Dockerfile.build -t ghcr.io/comocheng/kineticmodelssite/kms-build:latest .
      - name: push
        run: |
          docker push ghcr.io/comocheng/kineticmodelssite/kms-build:latest
